---
version: 2
updates:
  - package-ecosystem: "docker"  # docker
    directories: ["."]
    rebase-strategy: "auto"
    reviewers: ["caseysparkz"]
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:45"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "chore(docker)"

  - package-ecosystem: "docker-compose"  # docker-compose
    directories: ["."]
    rebase-strategy: "auto"
    reviewers: ["caseysparkz"]
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:45"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "chore(docker-compose)"

  - package-ecosystem: "github-actions"  # github-actions
    directories: [".github/workflows"]
    rebase-strategy: "auto"
    reviewers: ["caseysparkz"]
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:45"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "chore(github-actions)"

  - package-ecosystem: "gitsubmodule"  # git submodule
    directories: ["."]
    rebase-strategy: "auto"
    reviewers: ["caseysparkz"]
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:45"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "chore(gitsubmodule)"

  - package-ecosystem: "npm"  # NPM/Yarn
    directories: ["."]
    rebase-strategy: "auto"
    reviewers: ["caseysparkz"]
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:45"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "chore(npm-yarn)"

  - package-ecosystem: "pip"  # pip
    directories: ["."]
    rebase-strategy: "auto"
    reviewers: ["caseysparkz"]
    target-branch: "main"
    versioning-strategy: "increase-if-necessary"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:45"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "chore(python-pip)"

  - package-ecosystem: "terraform"  # terraform
    directories: ["."]
    rebase-strategy: "auto"
    reviewers: ["caseysparkz"]
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:45"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "chore(terraform)"
