---
version: 2
updates:
  - package-ecosystem: "github-actions"  # github-actions
    directories: [".github/workflows"]
    rebase-strategy: "auto"
    reviewers: ["caseysparkz"]
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:45"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "chore(github-actions)"

  - package-ecosystem: "npm"  # NPM/Yarn
    directories: ["caseysparkz.com/frontends/www"]
    rebase-strategy: "auto"
    reviewers: ["caseysparkz"]
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:45"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "chore(npm-yarn)"
