[mypy]
mypy_path = $MYPY_CONFIG_FILE_DIR
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true
files = [**/*.py, .dagger/**/*.py]
exclude = (?x)(^.dagger/sdk/)
