---
# Site, environment, locale variables -----------------------------------------
title: 'caseyspar.kz'
baseurl: 'https://www.caseyspar.kz'
environment: 'production'
defaultcontentlanguage: 'en'
enablerobotstxt: true
languagecode: 'en-us'

# Directory definitions -------------------------------------------------------
archetypedir: 'archetypes'
assetdir: 'assets'
contentdir: 'content'
datadir: 'data'
i18ndir: 'i18n'
layoutdir: 'layouts'
publishdir: 'public'
resourcedir: 'resources'
staticdir: ['static']
themesdir: 'themes'

# Global site settings --------------------------------------------------------
canonifyurls: true
capitalizelisttitles: true
enablegitinfo: true
paginate: 12
paginatepath: 'page'
pluralizelisttitles: true
summarylength: 70
timeout: '30s'
titlecasestyle: 'AP'

# Website settigs and parameters ----------------------------------------------
menus:
    main:
        - identifier: 'resume'
          name: 'Resume'
          pre: 'dropdown'
          weight: 01
        - identifier: 'blog'
          name: 'Blog'
          pre: 'dropdown'
          weight: 02
        - identifier: 'misc'
          name: 'Misc.'
          pre: 'dropdown'
          url: '/misc/'
          weight: 03
        - identifier: 'social'
          name: 'Social'
          pre: 'dropdown'
          url: '/social/'
          weight: 04
        - identifier: 'about'
          name: 'About'
          url: '/about/'
          weight: 05
    resume:
        - identifier: 'resume_html'
          name: 'HTML'
          url: '/resume/casey_sparks'
          weight: 01
        - identifier: 'resume_pdf'
          name: 'PDF'
          url: '/resume/casey_sparks.pdf'
          weight: 02
    blog:
        - identifier: 'code'
          name: 'Code'
          url: '/tags/code/'
          weight: 01
        - identifier: 'music'
          name: 'Music'
          url: '/tags/music/'
          weight: 02
    misc:
        - identifier: 'magazine'
          name: 'Intergalactic Observer'
          url: '/intergalactic_observer/'
          weight: 01
    social:
        - identifier: 'github'
          name: 'Github'
          url: 'https://github.com/caseysparkz'
          weight: 01
        - identifier: 'linkedin'
          name: 'LinkedIn'
          url: 'https://linkedin.com/in/caseysparkz'
          weight: 02
    footer:
        - identifier: 'about'
          name: 'About'
          url: '/about/'
          weight: 01
        # - identifier: 'contact'                                               # TODO
        #   name: 'Contact'
        #   url: '/contact/'
        #   weight: 99
params:
    author: 'Casey Sparks'
    authorimage: '../assets/images/global/caseysparkz.jpg'
    disable_stay_uptodate: true
    moto: 'Enthusiast.'
    og_image: '../assets/images/global/caseysparkz.jpg'
    p1:
        heading: 'Mission Statement???'
        image: 'images/pages/subhero.jpeg'
        content:
            - text: 'idk man, probably:'
            - text: '1. Replace the boilerplate Tailwinds artifacts.'
            - text: '2. Fix the contact form.'
            - text: '3. Figure out what to write here.'
            - text: '4. Stay posting.'
    # p2:                                                                       # TODO
    #     heading: ''
    #     image: ''
    #     content: [text: '']
    # p3:                                                                       # TODO
    #     heading: ''
    #     image: ''
    #     content: [text: '']
    p4:
        heading: 'From the blog'
        content:
            - text: "Mostly just what music I'm listening to. Sometimes code or project case studies."

# Misc. Hugo settings ---------------------------------------------------------
build:
    useresourcecachewhen: 'fallback'
    cachebusters:
        source: '(postcss|tailwind)\.config\.js'
        target: '(css|styles|scss|sass)'
caches:
    assets:
        dir: ':resourceDir/_gen'
        maxage: -1
    getcsv:
        dir: ':cacheDir/:project'
        maxage: -1
    getjson:
        dir: ':cacheDir/:project'
        maxage: -1
    getresource:
        dir: ':cacheDir/:project'
        maxage: -1
    images:
        dir: ':resourceDir/_gen'
        maxage: -1
    modules:
        dir: ':cacheDir/modules'
        maxage: -1
deployment:
    invalidatecdn: true                                                         # TODO
    maxdeletes: 256
    workers: 10
frontmatter:
    date:
        - 'date'
        - 'lastmod'
        - 'modified'
        - 'pubdate'
        - 'publishdate'
        - 'published'
    expirydate:
        - 'expirydate'
        - 'unpublishdate'
    lastmod:
        - ':git'
        - 'date'
        - 'lastmod'
        - 'modified'
        - 'pubdate'
        - 'publishdate'
        - 'published'
    publishdate:
        - 'publishdate'
        - 'pubdate'
        - 'published'
        - 'date'
imaging:
    bgcolor: '#ffffff'
    hint: 'photo'
    quality: 100                                                                # TODO: 75
    resamplefilter: 'box'
languages.en.languagecode: 'en-us'
markup:
    defaultmarkdownhandler: 'goldmark'
    asciidocext:
        backend: 'html5'
        failurelevel: 'fatal'
        noheaderorfooter: false
        safemode: 'unsafe'
    goldmark:
        extensions:
            definitionlist: true
            footnote: true
            linkify: true
            linkifyprotocol: 'https'
            strikethrough: true
            table: true
            tasklist: true
            cjk.eastasianlinebreaksstyle: 'simple'
            extras:
                insert:
                mark:
                subscript:
                superscript:
            typographer:
                apostrophe: '&rsquo;'
                ellipsis: '&hellip;'
                emdash: '&mdash;'
                endash: '&ndash;'
                leftanglequote: '&laquo;'
                leftdoublequote: '&ldquo;'
                leftsinglequote: '&lsquo;'
                rightanglequote: '&raquo;'
                rightdoublequote: '&rdquo;'
                rightsinglequote: '&rsquo;'
        parser:
            autoheadingid: true
            autoheadingidtype: 'github'
            wrapstandaloneimagewithinparagraph: true
            attribute.title: true
        renderer.unsafe: true
    highlight:
        codefences: true
        linenostart: 1
        linenumbersintable: true
        noclasses: true
        style: 'monokai'
        tabwidth: 4
    tableofcontents:
        endlevel: 3
        startlevel: 2
mediatypes:
    'application/json':
        delimiter: '.'
        suffixes: ['json']
    'application/manifest+json':
        delimiter: '.'
        suffixes: ['webmanifest']
    'application/octet-stream':
        delimiter: '.'
    'application/pdf':
        delimiter: '.'
        suffixes: ['pdf']
    'application/rss+xml':
        delimiter: '.'
        suffixes: ['rss', 'xml']
    'application/toml':
        delimiter: '.'
        suffixes: ['toml']
    'application/wasm':
        delimiter: '.'
        suffixes: ['wasm']
    'application/xml':
        delimiter: '.'
        suffixes: ['xml']
    'application/yaml':
        delimiter: '.'
        suffixes: ['yaml', 'yml']
    'font/otf':
        delimiter: '.'
        suffixes: ['otf']
    'font/ttf':
        delimiter: '.'
        suffixes: ['ttf']
    'image/bmp':
        delimiter: '.'
        suffixes: ['bmp']
    'image/gif':
        delimiter: '.'
        suffixes: ['gif']
    'image/jpeg':
        delimiter: '.'
        suffixes: ['jfif', 'jif', 'jpe', 'jpeg', 'jpg']
    'image/png':
        delimiter: '.'
        suffixes: ['png']
    'image/svg+xml':
        delimiter: '.'
        suffixes: ['svg']
    'image/tiff':
        delimiter: '.'
        suffixes: ['tif', 'tiff']
    'image/webp':
        delimiter: '.'
        suffixes: ['webp']
    'text/asciidoc':
        delimiter: '.'
        suffixes: ['ad', 'adoc', 'asciidoc']
    'text/calendar':
        delimiter: '.'
        suffixes: ['ics']
    'text/css':
        delimiter: '.'
        suffixes: ['css']
    'text/csv':
        delimiter: '.'
        suffixes: ['csv']
    'text/html':
        delimiter: '.'
        suffixes: ['htm', 'html']
    'text/javascript':
        delimiter: '.'
        suffixes: ['js', 'jsm', 'mjs']
    'text/jsx':
        delimiter: '.'
        suffixes: ['jsx']
    'text/markdown':
        delimiter: '.'
        suffixes: ['markdown', 'md', 'mdown']
    'text/org':
        delimiter: '.'
        suffixes: ['org']
    'text/pandoc':
        delimiter: '.'
        suffixes: ['pandoc', 'pdc']
    'text/plain':
        delimiter: '.'
        suffixes: ['txt']
    'text/rst':
        delimiter: '.'
        suffixes: ['rst']
    'text/tsx':
        delimiter: '.'
        suffixes: ['tsx']
    'text/typescript':
        delimiter: '.'
        suffixes: ['ts']
    'text/x-sass':
        delimiter: '.'
        suffixes: ['sass']
    'text/x-scss':
        delimiter: '.'
        suffixes: ['scss']
    'video/3gpp':
        delimiter: '.'
        suffixes: ['3gp', '3gpp']
    'video/mp4':
        delimiter: '.'
        suffixes: ['mp4']
    'video/mpeg':
        delimiter: '.'
        suffixes: ['mpeg', 'mpg']
    'video/ogg':
        delimiter: '.'
        suffixes: ['ogv']
    'video/webm':
        delimiter: '.'
        suffixes: ['webm']
    'video/x-msvideo':
        delimiter: '.'
        suffixes: ['avi']
minify.tdewolff:
    css.keepcss2: true
    html:
        keepdefaultattrvals: true
        keepdocumenttags: true
        keependtags: true
        keepspecialcomments: true
        templatedelims: ['', '']
    js.version: 2022
module:
    noproxy: 'none'
    private: '*.*'
    proxy: 'direct'
    workspace: 'off'
    hugoversion:
        extended: true
        min: '0.125.7'
    mounts:
        - source: 'tailwind.config.js'
          target: 'assets/_jsconfig/tailwind.config.js'
        - source: 'postcss.config.js'
          target: 'assets/_jsconfig/postcss.config.js'
        - source: 'package.json'
          target: 'assets/_jsconfig/package.json'
        - source: 'content'
          target: 'content'
        - source: 'data'
          target: 'data'
        - source: 'layouts'
          target: 'layouts'
        - source: 'i18n'
          target: 'i18n'
        - source: 'archetypes'
          target: 'archetypes'
        - source: 'assets'
          target: 'assets'
        - source: 'static'
          target: 'static'
outputformats:
    amp:
        basename: 'index'
        ishtml: true
        mediatype: 'text/html'
        path: 'amp'
        permalinkable: true
        rel: 'amphtml'
    calendar:
        basename: 'index'
        isplaintext: true
        mediatype: 'text/calendar'
        protocol: 'webcal://'
        rel: 'alternate'
    css:
        basename: 'styles'
        isplaintext: true
        mediatype: 'text/css'
        notalternative: true
        rel: 'stylesheet'
    csv:
        basename: 'index'
        isplaintext: true
        mediatype: 'text/csv'
        rel: 'alternate'
    html:
        basename: 'index'
        ishtml: true
        mediatype: 'text/html'
        permalinkable: true
        rel: 'canonical'
        weight: 10
    json:
        basename: 'index'
        isplaintext: true
        mediatype: 'application/json'
        rel: 'alternate'
    markdown:
        basename: 'index'
        isplaintext: true
        mediatype: 'text/markdown'
        rel: 'alternate'
    robots:
        basename: 'robots'
        isplaintext: true
        mediatype: 'text/plain'
        rel: 'alternate'
        root: true
    rss:
        basename: 'index'
        mediatype: 'application/rss+xml'
        nougly: true
        rel: 'alternate'
    sitemap:
        basename: 'sitemap'
        mediatype: 'application/xml'
        rel: 'sitemap'
        ugly: true
    webappmanifest:
        basename: 'manifest'
        isplaintext: true
        mediatype: 'application/manifest+json'
        notalternative: true
        rel: 'manifest'
outputs:
    home: ['html', 'rss']
    page: ['html']
    rss: ['rss']
    section: ['html', 'rss']
    taxonomy: ['html', 'rss']
    term: ['html', 'rss']
privacy:
    disqus.disable: true
    googleanalytics.disable: true
    instagram.disable: true
    twitter.disable: true
    vimeo.disable: true
    youtube.disable: true
related:
    threshold: 80
    indices:
        - name: 'date'
          type: 'basic'
          weight: 10
        - name: 'tags'
          type: 'basic'
          weight: 80
        - name: 'keywords'
          type: 'basic'
          weight: 99
security:
    enableinlineshortcodes: true
    exec:
        allow:
            - '^(dart-)?sass(-embedded)?$'
            - '^go$'
            - '^npx$'
            - '^postcss$'
        osenv:
            - '(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$'
    funcs.getenv: ['^HUGO_', '^CI$']
    http:
        methods: ['(?i)GET|POST']
        urls: ['.*']
server.redirects:
    from: '**'
    status: 404
    to: '/404.html'
services.rss.limit: -1
sitemap:
    filename: 'sitemap.xml'
    priority: -1
taxonomies:
    category: 'Categories'
    tag: 'Tags'
...
