---
- name: 'IPtables.'
  become: true
  tags:
      - 'firewall'
      - 'iptables'
  block:
      - name: 'Flush filters.'
        ansible.builtin.iptables:
            chain: '{{ item }}'
            flush: true
        loop:
            - 'INPUT'
            - 'FORWARD'
            - 'OUTPUT'

      - name: 'Set default chain policies.'
        ansible.builtin.iptables:
            action: '{{ item.action }}'
            chain: '{{ item.chain }}'
            policy: '{{ item.policy }}'
        loop:
            - {'action': 'insert', 'chain': 'INPUT', 'policy': 'DROP'}
            - {'action': 'insert', 'chain': 'OUTPUT', 'policy': 'ACCEPT'}
            - {'action': 'insert', 'chain': 'FORWARD', 'policy': 'DROP'}

      - name: 'Allow related and established connections.'
        ansible.builtin.iptables:
            chain: 'INPUT'
            ctstate: 'ESTABLISHED,RELATED'
            jump: 'ACCEPT'
...
