# Author:       Casey Sparks
# Date:         July 31, 2024
# Description:  Alpine 3.20.2
---
services:
  alpine:
    image: "770088062852.dkr.ecr.us-west-2.amazonaws.com/alpine3:0.0.1"
    build:
      context: "."
      dockerfile: "alpine3.Dockerfile"
      platforms: ["linux/amd64"]
      network: "host"
      labels:
        com.caseysparkz.registry: "770088062852.dkr.ecr.us-west-2.amazonaws.com"
        com.caseysparkz.name: "alpine3"
        com.caseysparkz.version: "0.0.1"
        com.caseysparkz.os.name: "alpine"
        com.caseysparkz.os.version: "3.20.2"
        com.caseysparkz.architecture: "amd64"
        com.caseysparkz.description: "Base Alpine 3 image."
        com.caseysparkz.maintainer.author.name: "Casey Sparks"
        com.caseysparkz.maintainer.author.email: "docker@caseysparkz.com"
