# Author:       Casey Sparks
# Date:         August 27, 2026
# Description:  Dagger GitHub image.
---
services:
  debian:
    image: "770088062852.dkr.ecr.us-west-2.amazonaws.com/dagger_github:0.0.1"
    build:
      context: "."
      dockerfile: "dagger_github.Dockerfile"
      platforms: ["linux/amd64"]
      network: "host"
      labels:
        com.caseysparkz.registry: "770088062852.dkr.ecr.us-west-2.amazonaws.com"
        com.caseysparkz.name: "dagger_github"
        com.caseysparkz.version: "0.0.1"
        com.caseysparkz.os.name: "debian"
        com.caseysparkz.os.version: "13"
        com.caseysparkz.architecture: "amd64"
        com.caseysparkz.description: "Dagger GitHub image."
        com.caseysparkz.maintainer.author.name: "Casey Sparks"
        com.caseysparkz.maintainer.author.email: "docker@caseysparkz.com"
