# Author:       Casey Sparks
# Date:         August 27, 2026
# Description:  Debian 13 image
---
services:
  debian:
    image: "ecr.caseysparkz.com/debian13:0.0.1"
    build:
      context: "."
      dockerfile: "debian13.Dockerfile"
      platforms: ["linux/amd64"]
      network: "host"
      labels:
        com.caseysparkz.registry: "ecr.caseysparkz.com"
        com.caseysparkz.name: "debian13"
        com.caseysparkz.version: "0.0.1"
        com.caseysparkz.os.name: "debian"
        com.caseysparkz.os.version: "13"
        com.caseysparkz.architecture: "amd64"
        com.caseysparkz.description: "Base Debian 13 image."
        com.caseysparkz.maintainer.author.name: "Casey Sparks"
        com.caseysparkz.maintainer.author.email: "docker@caseysparkz.com"
