---
- name: "Install template directory"
  tags: ["git"]
  ansible.builtin.file:
    src: "{{ git_symlink_src_dir }}/files/git_template"
    dest: "{{ ansible_facts.env.HOME }}/.git_template"
    owner: "{{ ansible_facts.effective_user_id }}"
    group: "{{ ansible_facts.effective_group_id }}"
    state: "link"
    force: true

- name: "Configure git"
  tags: ["git"]
  ansible.builtin.file:
    src: "{{ git_symlink_src_dir }}/files/gitconfig"
    dest: "{{ ansible_facts.env.HOME }}/.gitconfig"
    owner: "{{ ansible_facts.effective_user_id }}"
    group: "{{ ansible_facts.effective_group_id }}"
    state: "link"
    force: true

- name: "Configure gh"
  tags:
    - "gh"
    - "git"
  ansible.builtin.file:
    src: "{{ git_symlink_src_dir }}/files/config/gh"
    dest: "{{ ansible_facts.env.HOME }}/.config/gh"
    owner: "{{ ansible_facts.effective_user_id }}"
    group: "{{ ansible_facts.effective_group_id }}"
    state: "link"
    force: true
