# Author:       Casey Sparks
# Date:         July 31, 2024
# Description:  Python 3.11.2 image
---
services:
  python3:
    image: "770088062852.dkr.ecr.us-west-2.amazonaws.com/python3.11:0.0.1"
    build:
      context: "."
      platforms: ["linux/amd64"]
      network: "host"
      args:
        REGISTRY: "770088062852.dkr.ecr.us-west-2.amazonaws.com"
        IMAGE: "debian12"
        VERSION: "0.0.1"
        PYTHON_UNBUFFERED: 1
      labels:
        kz.caseyspar.registry: "770088062852.dkr.ecr.us-west-2.amazonaws.com"
        kz.caseyspar.name: "python3.11"
        kz.caseyspar.version: "0.0.1"
        kz.caseyspar.os.name: "debian"
        kz.caseyspar.os.version: "12"
        kz.caseyspar.architecture: "amd64"
        kz.caseyspar.description: "Base Python 3.11 image."
        kz.caseyspar.maintainer.author.name: "Casey Sparks"
        kz.caseyspar.maintainer.author.email: "docker@caseyspar.kz"
        kz.caseyspar.app.name: "python"
        kz.caseyspar.app.version: "3.11.2"
        kz.caseyspar.app.version.major: 3
        kz.caseyspar.app.version.minor: 11
        kz.caseyspar.app.version.revision: 2
      dockerfile_inline: |
        ARG REGISTRY
        ARG IMAGE
        ARG VERSION

        FROM "$${REGISTRY}/$${IMAGE}:$${VERSION}"

        ARG PYTHON_UNBUFFERED

        ENV PYTHON_UNBUFFERED="$${PYTHON_UNBUFFERED}"

        USER root

        RUN true                                                              \
          && apt-get update                                                   \
          && apt-get install --assume-yes --no-install-recommends             \
            "python3=3.11.2-1+b1"                                             \
            "python3-boto3=1.26.27+dfsg-1"                                    \
            "python3-boto=2.49.0-4.1"                                         \
            "python3-dateutil=2.8.2-2"                                        \
            "python3-jinja2=3.1.2-1+deb12u2"                                  \
            "python3-requests=2.28.1+dfsg-1"                                  \
          && rm --recursive --force                                           \
            /var/cache/apt/*                                                  \
          && update-alternatives --install                                    \
            /usr/bin/python                                                   \
            python                                                            \
            /usr/bin/python3                                                  \
            0

        USER "$${APP_USER}"

        ENTRYPOINT ["/usr/bin/python3"]
