# Author:       Casey Sparks
# Date:         November 13, 2024
# Description:  Label a pull request with the correct tags.
---
name: "Label Pull Request"
on: ["pull_request"]
jobs:
  label:
    name: "Label Rull Request"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      pull-requests: "write"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"  # v6.0.2
        with:
          fetch-depth: 0

      - name: "Get commit message tags"
        id: "commit_msgs"
        run: |
          readarray -t COMMIT_TAGS < <(                                                                             \
            git log origin/${{ github.event.pull_request.base.ref }}..HEAD --pretty='%s'                            \
            | grep -E '^(build|chore|ci|docs|feat|fix|perf|refactor|style|revert|test)[:(].*$'                      \
            | sed 's/[:(].*$//g'                                                                                    \
            | sort                                                                                                  \
            | uniq                                                                                                  \
          )

          echo "labels=$(jq -c -n '$ARGS.positional' --args "${COMMIT_TAGS[@]}")" >> "${GITHUB_OUTPUT}"

      - name: "Label pull request"
        uses: "actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd" #v8.0.0
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ${{ steps.commit_msgs.outputs.labels }}
            })

      - name: "Auto-label"
        uses: "actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b"  # v6.0.1
        with:
          repo-token: "${{ github.token }}"
          configuration-path: ".github/config/labeler.yml"
          sync-labels: false
          dot: true
          pr-number: "${{ github.event.pull_request.number }}"
