# Author:       Casey Sparks
# Date:         September 03, 2024
# Description:  Ensure that Pull Request title adheres to the conventional commit syntax.
# Ref:          https://github.com/amannn/action-semantic-pull-request
---
name: "Conventional Pull Request Titles"
on:
  pull_request_target:
    types:
      - "edited"
      - "opened"
      - "reopened"
      - "synchronize"
permissions:
  pull-requests: "read"
jobs:
  conventional_pull_request:
    name: "Validate Pull Request Title"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check PR name compliance to conventional commits"
        uses: "amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017"
        with:
          requireScope: false
          headerPattern: "^(\\w*)(?:\\(([\\w$.\\-*/ ]*)\\))?: (.*)$"
          headerPatternCorrespondence: "type, scope, subject"
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            style
            test
          scopes: |                                                             # Regex patterns auto-wrapped in `^ $`
            .*
          ignoreLabels: |
            ignore-semantic-pull-request
