# Author:       Casey Sparks
# Date:         September 03, 2024
# Description:  Lint all Dockerfiles with Hadolint.
---
name: "Validate Dockerfiles and docker-compose files"
on:
  pull_request:
    branches: ["main"]
    paths:
      - "**/*Dockerfile"
      - "**/*docker-compose.yml"
jobs:
  hadolint:
    name: "Hadolint"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          fetch-depth: 0

      - name: "Lint Dockerfiles"
        uses: "hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf"
        with:
          dockerfile: "*Dockerfile"
          recursive: true
          no-color: true
          no-fail: false
          format: "tty"

  docker_compose_lint:
    name: "docker compose lint"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          fetch-depth: 0

      - name: "Set up docker compose"
        uses: "docker/setup-compose-action@364cc21a5de5b1ee4a7f5f9d3fa374ce0ccde746" # v1.2.0
        with:
          version: "latest"

      - name: "Lint docker-compose files"
        run: "for FILE in ./*.docker-compose.yml; do docker compose -f \"${FILE}\" config; done"
        working-directory: "caseyspar.kz/docker_compose/"
        with:
          version: "latest"

# docker_compose_push:                                                          # TODO
#   name: "Push Docker images to ECR"
#   runs-on: "ubuntu-latest"
#   steps:
#     - name: "Checkout"
#       uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
#       with:
#         fetch-depth: 0
