# Author:       Casey Sparks
# Date:         June 06, 2024
# Description:  Run yamllint against all YAML files in the repository.
---
name: "Validate YAML files"
on:
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - ".github/workflows/yaml.yml"
jobs:
  yamllint:
    name: "Yamllint"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8"  # v5.0.0
        with:
          fetch-depth: 0

      - name: "Yamllint"
        uses: "karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2"  # v3.0.0
        with:
          yamllint_file_or_dir: "./"
          yamllint_strict: true
          yamllint_comment: true
          yamllint_config_filepath: ".github/config/yamllint.yml"
