# Author:       Casey Sparks
# Date:         June 06, 2024
# Description:  Run dagger yamlchecks
---
name: "yaml"
on:
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.yaml"
      - "**/*.yml"
env:
  AWS_DEFAULT_REGION: "us-west-2"
jobs:
  dagger_check_yaml:
    name: "dagger"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: "git checkout"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          fetch-depth: 2

      - name: "aws sso login"
        uses: "aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c"  # v6.2.3
        with:
          aws-region: "${{ env.AWS_DEFAULT_REGION }}"
          role-to-assume: "${{ secrets.AWS_ROLE_ARN }}"
          role-session-name: "gha-${{ github.run_id }}"

      - name: "dagger check yaml:*"
        uses: "./.github/actions/dagger-check"
        with:
          filter: "yaml:*"
